version: "3.8"
services:
  frontend:
    build: ./frontend
    image: ${DOCKER_HUB_CREDS_USR}/library-frontend:latest
    container_name: library-frontend
    ports:
    - target: 5000
      published: 80
  backend:
    build: ./backend
    image: ${DOCKER_HUB_CREDS_USR}/library-backend:latest
    container_name: library-backend
    environment:
      DATABASE_URI:
      CREATE_SCHEMA:
   